### ISSUE TITLE
Run CLDF conversion and check

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/gata#7]
@MuffinLinwist, what is the status on teh cldf conversion, are there any errors now?

**Comment by LinguList** [comment]
Should I check from my side?

**Comment by CMUgarte** [comment]
I have run the command and it gives me this error:
ValueError: tables must have distinct url properties

**Comment by CMUgarte** [comment]
Yes, please. I didn't get this error the other times I run it.

**Comment by LinguList** [comment]
Please check now, @MuffinLinwist, I made all necessary changes, and it runs now. Please let me know if there are questions. Basically, the strategy was not correct. It would have been better to check with actual cldf dataset conversions, where you can see the difference between `add_component` and `add_column`, but also the namespace was quite a problem here, as columns were re-defined, although these components, like a languagetable, come with predefined columns.

But this is all fixed now, and the code is also smaller ;)

**Comment by CMUgarte** [comment]
Thanks, @LinguList , for the modifications! The dataset is so much better now. I have one question:

- It is still not clear to me why adding something as a component or as a column. When I put: `data_fnames={"ParameterTable": "parameters.csv", "LanguageTable": "languages.csv"}`, and add the LanguageTable as a column, it yields the same result. Why choosing one or another? I thought that components are for data re-used across modules. If that's the case, then why the different coding between the two tables?

**Comment by LinguList** [comment]
It yields the same results, so you choose whatever you like.

**Comment by CMUgarte** [comment]
Great :)

**Comment by FredericBlum** [comment]
The CLDF conversion runs smoothly and we can close this issue, right? #10 is independent from this?
